<?php
use \Model\Day\Day;
use \Model\Store\Store;
use \Model\Store\Social\Social;
use \Model\Store\Address\Address;
use \Model\Store\Contact\Contact;
use \Model\Store\Schedule\Schedule;
use \Model\Store\Schedule\DaySchedule;
use \Model\Store\Schedule\DayScheduleSection;

$store = $params["store"];
$social = $store->GetSocial();
$address = $store->GetAddress();
$contact = $store->GetContact();
$schedule = $store->GetSchedule();
?>

<section class="l-content content">
	<section class="about__tiles-content">
		<section class="about__tile--schedule">
			<h1 class="about__tile__title--schedule">Nos horaires</h1>
			<section class="about__tile__content">
			<table>
<?php foreach ($schedule->GetDaySchedules() as $daySchedule) : ?>
				<tr>
					<td><?= $daySchedule->GetDay()->GetLabel();?></td>
					<td>:</td>
					<td>
	<?php if ($daySchedule->IsOpen()): ?>
		<?php $i=0; ?>
		<?php foreach ($daySchedule->GetSections() as $section): ?>
						<?= $i > 0 ? '/' : '' ?> 
						<?= $section->GetStartingTime()->format('H:i') ?>-<?= $section->GetEndingTime()->format('H:i') ?>
			<?php $i++; ?>
		<?php endforeach; ?>
	<?php else: ?>
						<i class="fas fa-times"></i>
	<?php endif; ?>
					</td>
				</tr>
<?php endforeach; ?>
			</table>
			</section>
		</section>

		<section class="about__tile--contact">
			<h1 class="about__tile__title--contact">Nous contacter</h1>
			<section class="about__tile__content">
				<span><i class="fas fa-at"></i></span>
				<p><a href="mailto:<?= $contact->GetEmail(); ?>"><?= $contact->GetEmail(); ?></a></p>
				<span><i class="fab fa-facebook-messenger"></i></span>
				<p><a href="<?= $contact->GetMessenger(); ?>">Messenger</a></p>
				<span><i class="fas fa-phone"></i></span>
				<p><a href="tel:<?= $contact->GetPhoneNumber(); ?>"><?= $contact->GetPhoneNumber(); ?></a></p>
			</section>
		</section>

		<section class="about__tile--find">
			<h1 class="about__tile__title--find">Nous trouver</h1>
			<section class="about__tile__content">
				<address>
					<p><?= $address->GetSocialReason(); ?></p>
					<p><?= $address->GetLine1(); ?></p>
<?php if ($address->HasLine2()): ?>
					<p><?= $address->GetLine2(); ?></p>
<?php endif; ?>
<?php if ($address->HasLine3()): ?>
					<p><?= $address->GetLine3(); ?></p>
<?php endif; ?>
					<p><?= $address->GetPostalCode(); ?> <?= $address->GetCity(); ?></p>
				</address>
			</section>
		</section>
			
		<section class="about__tile--follow">
			<h1 class="about__tile__title--follow">Nous suivre</h1>
			<section class="about__tile__content">
				<a class="button--facebook" href="https://www.facebook.com/La-Forge-dAudren-164158920348705"></a>
				<a class="button--twitter" href="https://twitter.com/LaForgedAudren"></a>
				<a class="button--youtube" href="https://www.youtube.com/channel/UCuSOG6fpU1ymvx3yzbBrlUQ"></a>
				<a class="button--instagram" href="https://www.instagram.com/renaudlepage/"></a>
			</section>
		</section>
	</section>
</section>