<?php
use \Model\Day\Day;
use \Model\Store\Store;
use \Model\Store\Social\Social;
use \Model\Store\Address\Address;
use \Model\Store\Contact\Contact;
use \Model\Store\Schedule\Schedule;
use \Model\Store\Schedule\DaySchedule;
use \Model\Store\Schedule\DayScheduleSection;

$store = $params["store"];
$social = $store->GetSocial();
$address = $store->GetAddress();
$contact = $store->GetContact();
$schedule = $store->GetSchedule();
?>

<section class="l-content content">
<article>
		<header>
			<h2>Contact</h2>
		</header>
		<section>
			<section>
				<h3><span><i class="far fa-calendar-alt"></i></span> Nos horaires</h3>
				<table>
<?php foreach ($schedule->GetDaySchedules() as $daySchedule) : ?>
					<tr>
						<td><?= $daySchedule->GetDay()->GetLabel();?></td>
						<td>:</td>
						<td>
	<?php if ($daySchedule->IsOpen()): ?>
		<?php $i=0; ?>
		<?php foreach ($daySchedule->GetSections() as $section): ?>
							<?= $i > 0 ? '/' : '' ?> 
							<?= $section->GetStartingTime()->format('H:i') ?>-<?= $section->GetEndingTime()->format('H:i') ?>
			<?php $i++; ?>
		<?php endforeach; ?>
	<?php else: ?>
							Fermé
	<?php endif; ?>
						</td>
					</tr>
<?php endforeach; ?>
				</table>
			</section>

			<section>
				<h3><span><i class="fas fa-envelope"></i></span> Nous contacter</h3>
				<span><i class="fas fa-at"></i></span>
				<p><a href="mailto:<?= $contact->GetEmail(); ?>"><?= $contact->GetEmail(); ?></a></p>
				<span><i class="fab fa-facebook-messenger"></i></span>
				<p><a href="<?= $contact->GetMessenger(); ?>">Messenger</a></p>
				<span><i class="fas fa-phone"></i></span>
				<p><a href="tel:<?= $contact->GetPhoneNumber(); ?>"><?= $contact->GetPhoneNumber(); ?></a></p>
			</section>

			<section>
				<h3><span><i class="fas fa-map-marker-alt"></i></span> Nous trouver</h3>
				<address>
					<p><?= $address->GetSocialReason(); ?></p>
					<p><?= $address->GetLine1(); ?></p>
<?php if ($address->HasLine2()): ?>
					<p><?= $address->GetLine2(); ?></p>
<?php endif; ?>
<?php if ($address->HasLine3()): ?>
					<p><?= $address->GetLine3(); ?></p>
<?php endif; ?>
					<p><?= $address->GetPostalCode(); ?> <?= $address->GetCity(); ?></p>
				</address>
			</section>
			
			<section>
				<h3><span><i class="fas fa-share-alt"></i></span> Nous suivre</h3>
				<a href="https://www.facebook.com/La-Forge-dAudren-164158920348705"><i class="fab fa-facebook"></i></a>
				<a href="https://twitter.com/LaForgedAudren"><i class="fab fa-twitter"></i></a>
				<a href="https://www.youtube.com/channel/UCuSOG6fpU1ymvx3yzbBrlUQ"><i class="fab fa-youtube"></i></a>
				<a href="https://www.instagram.com/renaudlepage/"><i class="fab fa-instagram"></i></a>
			</section>
		</section>
	</article>
</section>