<?php
use \Framework\Tools\Helper\RoutesHelper;
use \Model\Store\Store;
use \Model\Store\Contact\Contact;
use \Model\Store\Address\Address;

$store = $params["store"];
$social = $store->GetSocial();
$contact = $store->GetContact();
$address = $store->GetAddress();
$schedule = $store->GetSchedule();
?>

<script type="text/javascript" src="../Assets/js/module/store/store-manager.js"></script>

<section class="l-content content">
	<form id="store-form" class="form" action="<?= $_SERVER['REQUEST_URI'] ?>" method="POST">
		<h1>Gérer les informations du magasin</h1>
		<section>
			<section class="form__content">
				<h2>Social</h2>
				<section class="form__validation-container">
					<section class="form__input-container">
						<label class="form__input-container__label" for="store-social-facebooklink">Facebook</label>
						<input class="form__input-container__input" type="text" id="store-contact-facebooklink" name="store-contact-facebooklink" value="<?= $social->GetFacebookLink(); ?>">
					</section>
				</section>
				<section class="form__validation-container">
					<section class="form__input-container">
						<label class="form__input-container__label" for="store-social-twitterlink">Twitter</label>
						<input class="form__input-container__input" type="text" id="store-contact-twitterlink" name="store-contact-twitterlink" value="<?= $social->GetTwitterLink(); ?>">
					</section>
				</section>
				<div>
					<label for="store-social-youtubelink">Youtube</label>
					<input type="text" id="store-contact-youtubelink" name="store-contact-youtubelink" value="<?= $social->GetYoutubeLink(); ?>">
				</div>
				<div>
					<label for="store-social-instagramlink">Instagram</label>
					<input type="text" id="store-contact-instagramlink" name="store-contact-instagramlink" value="<?= $social->GetInstagramLink(); ?>">
				</div>
			</section>

			<section>
				<h2>Contact</h2>
				<div>
					<label for="store-contact-email">Email</label>
					<input type="text" id="store-contact-email" name="store-contact-email" value="<?= $contact->GetEmail(); ?>">
				</div>
				<div>
					<label for="store-contact-phonenumber">Numéro de téléphone</label>
					<input type="text" id="store-contact-phonenumber" name="store-contact-phonenumber" value="<?= $contact->GetPhoneNumber(); ?>">
				</div>
				<div>
					<label for="store-contact-messenger">Messenger</label>
					<input type="text" id="store-contact-messenger" name="store-contact-messenger" value="<?= $contact->GetMessenger(); ?>">
				</div>
			</section>

			<section>
				<h2>Addresse</h2>
				<div>
					<label for="store-address-socialreason">Raison sociale</label>
					<input type="text" id="store-address-socialreason" name="store-address-socialreason" value="<?= $address->GetSocialReason(); ?>">
				</div>
				<div>
					<label for="store-address-line1">Ligne 1</label>
					<input type="text" id="store-address-line1" name="store-address-line1" value="<?= $address->GetLine1(); ?>">
				</div>
				<div>
					<label for="store-address-line2">Ligne 2</label>
					<input type="text" id="store-address-line2" name="store-address-line2" value="<?= $address->GetLine2(); ?>">
				</div>
				<div>
					<label for="store-address-line3">Ligne 3</label>
					<input type="text" id="store-address-line3" name="store-address-line3" value="<?= $address->GetLine3(); ?>">
				</div>
				<div>
					<label for="store-address-postalcode">Code postal</label>
					<input type="text" id="store-address-postalcode" name="store-address-postalcode" value="<?= $address->GetPostalCode(); ?>">
				</div>
				<div>
					<label for="store-address-city">Ville</label>
					<input type="text" id="store-address-city" name="store-address-city" value="<?= $address->GetCity(); ?>">
				</div>
			</section>
			
			<section>
				<h2>Horaires</h2>
					<table>
<?php foreach ($schedule->GetDaySchedules() as $daySchedule): ?>
						<tr>
							<td><?= $daySchedule->GetDay()->GetLabel();?></td>
							<td>:</td>
							<td id="dayschedulesections-container-<?= $daySchedule->GetDay()->GetId(); ?>">
	<?php foreach ($daySchedule->GetSections() as $section): ?>
								<section id="dayschedulesection-<?= $daySchedule->GetDay()->GetId(); ?>-<?= $section->GetId(); ?>">
									<input type="text" id="store-schedule-<?= $daySchedule->GetDay()->GetId(); ?>-startingtime-<?= $section->GetId(); ?>" name="store-schedule-<?= $daySchedule->GetDay()->GetId(); ?>-startingtime-<?= $section->GetId(); ?>" value="<?= $section->GetStartingTime()->format('H:i') ?>"><!--
									-->-<!--
									--><input type="text" id="store-schedule-<?= $daySchedule->GetDay()->GetId(); ?>-endingtime-<?= $section->GetId(); ?>" name="store-schedule-<?= $daySchedule->GetDay()->GetId(); ?>-endingtime-<?= $section->GetId(); ?>" value="<?= $section->GetEndingTime()->format('H:i') ?>"><!--
									--><button class="delete-dayschedulesection-button" data-dayid="<?= $daySchedule->GetDay()->GetId(); ?>" data-dayschedulesectionid="<?= $section->GetId(); ?>">x</button>
								</section>
	<?php endforeach; ?>
							</td>
							<td>
								<button class="add-dayschedulesection-button" data-dayid="<?= $daySchedule->GetDay()->GetId(); ?>">+</button>
							</td>
						</tr>
<?php endforeach; ?>
					</table>
			</section>

			<section class="form__buttons">
				<ul>
					<li>
						<button class="button--save" type="submit">Enregister</button>
					</li>
				</ul>
			</section>
		</section>
	</form>
</section>