<?php
use \Framework\Tools\Helper\RoutesHelper;
use \Model\Store\Store;
use \Model\Store\Contact\Contact;
use \Model\Store\Address\Address;

$store = $params["store"];
$social = $store->GetSocial();
$contact = $store->GetContact();
$address = $store->GetAddress();
$schedule = $store->GetSchedule();
?>

<script type="text/javascript" src="../Assets/js/module/store/store-manager.js"></script>

<section class="l-content content">
	<form id="store-form" class="form" action="<?= $_SERVER['REQUEST_URI'] ?>" method="POST">
		<h1>Gérer les informations du magasin</h1>
		<section>
			<section class="form__content">
				<h2>Social</h2>
				<input type="hidden" id="store-social-id" name="store-social-id" value="<?= $social->GetId(); ?>">
				<section class="form__validation-container">
					<section class="form__input-container">
						<label class="form__input-container__label" for="store-social-facebooklink">Facebook</label>
						<input class="form__input-container__input" type="url" id="store-social-facebooklink" name="store-social-facebooklink" value="<?= $social->GetFacebookLink(); ?>" required>
					</section>
				</section>
				<section class="form__validation-container">
					<section class="form__input-container">
						<label class="form__input-container__label" for="store-social-twitterlink">Twitter</label>
						<input class="form__input-container__input" type="url" id="store-social-twitterlink" name="store-social-twitterlink" value="<?= $social->GetTwitterLink(); ?>" maxlength="500" required>
					</section>
				</section>
				<section class="form__validation-container">
					<section class="form__input-container">
						<label class="form__input-container__label" for="store-social-youtubelink">Youtube</label>
						<input class="form__input-container__input" type="url" id="store-social-youtubelink" name="store-social-youtubelink" value="<?= $social->GetYoutubeLink(); ?>" maxlength="500" required>
					</section>
				</section>
				<section class="form__validation-container">
					<section class="form__input-container">
						<label class="form__input-container__label" for="store-social-instagramlink">Instagram</label>
						<input class="form__input-container__input" type="url" id="store-social-instagramlink" name="store-social-instagramlink" value="<?= $social->GetInstagramLink(); ?>" maxlength="500" required>
					</section>
				</section>
			</section>

			<section>
				<h2>Contact</h2>
				<input type="hidden" id="store-contact-id" name="store-contact-id" value="<?= $contact->GetId(); ?>">
				<section class="form__validation-container">
					<section class="form__input-container">
						<label class="form__input-container__label" for="store-contact-email">Email</label>
						<input class="form__input-container__input" type="email" id="store-contact-email" name="store-contact-email" value="<?= $contact->GetEmail(); ?>" maxlength="200" required>
					</section>
				</section>
				<section class="form__validation-container">
					<section class="form__input-container">
						<label class="form__input-container__label" for="store-contact-phonenumber">Numéro de téléphone</label>
						<input class="form__input-container__input" type="tel" id="store-contact-phonenumber" name="store-contact-phonenumber" value="<?= $contact->GetPhoneNumber(); ?>" maxlength="20" required>
					</section>
				</section>
				<section class="form__validation-container">
					<section class="form__input-container">
						<label class="form__input-container__label" for="store-contact-messenger">Messenger</label>
						<input class="form__input-container__input" type="url" id="store-contact-messenger" name="store-contact-messenger" value="<?= $contact->GetMessenger(); ?>" maxlength="500">
					</section>
				</section>
			</section>

			<section>
				<h2>Addresse</h2>
				<input type="hidden" id="store-address-id" name="store-address-id" value="<?= $address->GetId(); ?>">
				<section class="form__validation-container">
					<section class="form__input-container">
						<label class="form__input-container__label" for="store-address-socialreason">Raison sociale</label>
						<input class="form__input-container__input" type="text" id="store-address-socialreason" name="store-address-socialreason" value="<?= $address->GetSocialReason(); ?>" maxlength="200" required>
					</section>
				</section>
				<section class="form__validation-container">
					<section class="form__input-container">
						<label class="form__input-container__label" for="store-address-line1">Ligne 1</label>
						<input class="form__input-container__input" type="text" id="store-address-line1" name="store-address-line1" value="<?= $address->GetLine1(); ?>" maxlength="200" required>
					</section>
				</section>
				<section class="form__validation-container">
					<section class="form__input-container">
						<label class="form__input-container__label" for="store-address-line2">Ligne 2</label>
						<input class="form__input-container__input" type="text" id="store-address-line2" name="store-address-line2" value="<?= $address->GetLine2(); ?>" maxlength="200">
					</section>
				</section>
				<section class="form__validation-container">
					<section class="form__input-container">
						<label class="form__input-container__label" for="store-address-line3">Ligne 3</label>
						<input class="form__input-container__input" type="text" id="store-address-line3" name="store-address-line3" value="<?= $address->GetLine3(); ?>" maxlength="200">
					</section>
				</section>
				<section class="form__validation-container">
					<section class="form__input-container">
						<label class="form__input-container__label" for="store-address-postalcode">Code postal</label>
						<input class="form__input-container__input" type="number" id="store-address-postalcode" name="store-address-postalcode" value="<?= $address->GetPostalCode(); ?>" maxlength="5" required>
					</section>
				</section>
				<section class="form__validation-container">
					<section class="form__input-container">
						<label class="form__input-container__label" for="store-address-city">Ville</label>
						<input class="form__input-container__input" type="text" id="store-address-city" name="store-address-city" value="<?= $address->GetCity(); ?>" maxlength="200" required>
					</section>
				</section>
			</section>
			
			<section>
				<h2>Horaires</h2>
				<input type="hidden" id="store-schedule-id" name="store-schedule-id" value="<?= $schedule->GetId(); ?>">
				<table>
<?php foreach ($schedule->GetDaySchedules() as $daySchedule): ?>
					<tr>
						<input type="hidden" id="store-schedule-dayschedule-id:<?= $daySchedule->GetId(); ?>-dayid:<?= $daySchedule->GetDay()->GetId(); ?>" name="store-schedule-dayschedule-id:<?= $daySchedule->GetId(); ?>-dayid:<?= $daySchedule->GetDay()->GetId(); ?>" value="<?= $daySchedule->GetId(); ?>">
						<td><?= $daySchedule->GetDay()->GetLabel(); ?></td>
						<td>:</td>
						<td id="dayschedulesections-container-<?= $daySchedule->GetDay()->GetId(); ?>">
	<?php foreach ($daySchedule->GetSections() as $section): ?>
							<section id="dayschedulesection-dayid:<?= $daySchedule->GetDay()->GetId(); ?>-dayschedulesectionid:<?= $section->GetId(); ?>">
								<input type="time" id="store-schedule-dayschedule-id:<?= $daySchedule->GetId(); ?>-dayid:<?= $daySchedule->GetDay()->GetId(); ?>-dayschedulesection-id:<?= $section->GetId(); ?>-startingtime" name="store-schedule-dayschedule-id:<?= $daySchedule->GetId(); ?>-dayid:<?= $daySchedule->GetDay()->GetId(); ?>-dayschedulesection-id:<?= $section->GetId(); ?>-startingtime" value="<?= $section->GetStartingTime()->format('H:i') ?>" required><!--
								-->-<!--
								--><input type="time" id="store-schedule-dayschedule-id:<?= $daySchedule->GetId(); ?>-dayid:<?= $daySchedule->GetDay()->GetId(); ?>-dayschedulesection-id:<?= $section->GetId(); ?>-endingtime" name="store-schedule-dayschedule-id:<?= $daySchedule->GetId(); ?>-dayid:<?= $daySchedule->GetDay()->GetId(); ?>-dayschedulesection-id:<?= $section->GetId(); ?>-endingtime" value="<?= $section->GetEndingTime()->format('H:i') ?>" required><!--
								--><button class="delete-dayschedulesection-button" data-dayid="<?= $daySchedule->GetDay()->GetId(); ?>" data-dayschedulesectionid="<?= $section->GetId(); ?>">x</button>
							</section>
	<?php endforeach; ?>
						</td>
						<td>
							<button class="add-dayschedulesection-button" data-dayid="<?= $daySchedule->GetDay()->GetId(); ?>" data-dayscheduleid="<?= $daySchedule->GetId(); ?>">+</button>
						</td>
					</tr>
<?php endforeach; ?>
				</table>
			</section>

			<section class="form__buttons">
				<ul>
					<li>
						<button class="button--save" type="submit">Enregister</button>
					</li>
				</ul>
			</section>
		</section>
	</form>
</section>